### ISSUE TITLE
goldmod exe

### ISSUE THREAD

**Issue by bengu1** [budspencer1/GoldMod-Cube2#1]
gold mod need scaned and cleaned ,and he need some fixes like commands mute cn kill cn ,and permision for master that sucks a master can shutdown the serv wtf::::?//i like that command adduser and deluser,so you should implement these commands spy invpriv and .about askidban same sucks vpn can conect also getlanguage same sucks so test it again and fix it better xd then find the solution for not crashing anymore ty ..yuri1

**Comment by budspencer1** [comment]
lol - first

**Comment by bengu1** [comment]
ioi spence

2016-11-17 23:14 GMT+02:00 Sebastian <3 <notifications@github.com>:

**Comment by bengu1** [comment]
and dont forgget im the first whoo use this mod xd but you the best bro
